#!/usr/bin/expect

set BASE_DIR .

set LOCAL_DIR "$BASE_DIR/../warships/bin-release/web/1"

set REMOTE_DIR "root@123.207.66.245:/usr/share/nginx/html/ship-loader-test"
set REMOTE_PASSWORD "dmmh5ship"

spawn scp -C -r $REMOTE_DIR/resource/default.res.json $BASE_DIR/default.res.json
expect "*password*"
send "$REMOTE_PASSWORD\r"
interact

spawn scp -C -r $REMOTE_DIR/resource/others.res.json $BASE_DIR/others.res.json
expect "*password*"
send "$REMOTE_PASSWORD\r"
interact
