#!/usr/bin/expect

set BASE_DIR .

set LOCAL_DIR "$BASE_DIR/../warships/bin-release/web/1"

set REMOTE_DIR "root@192.168.2.162:/data/web/client/cn"
set REMOTE_PASSWORD "HQFY123"

spawn scp -C -r $REMOTE_DIR/resource/default.res.json $BASE_DIR/default.res.json
expect "*password*"
send "$REMOTE_PASSWORD\r"
interact

spawn scp -C -r $REMOTE_DIR/resource/others.res.json $BASE_DIR/others.res.json
expect "*password*"
send "$REMOTE_PASSWORD\r"
interact
